### PR TITLE
Footer design to check before perfection

### PR DESCRIPTION
**Pull request by slowloris-x**
Here it is check it out to see if the way how I divide it is how you want it to be

### CODE REVIEW

**Comment by nishihere19** [comment]
Can you add a screenshot of the work? Also, try to avoid changes in package.json when you contribute in open-source. For this PR it is fine. Just a piece of advice.

**Comment by slowloris-x** [comment]
Thank you so much for the advice, I got an error trying to run your cose on my local : "Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)"
I had to downgrade Mongoose to get it fixed that why

**Comment by nishihere19** [comment]
Looks nice to me. I am merging it now. Further, You can add screenshots in PR itself in the comments like this.
Screen Shot 2021-03-22 at 16 33 04

**Comment by slowloris-x** [comment]
Thank you so much, that was very helpful, while designing the footer, there was some issues I noticed, among the critically one the "logout" isn't working (after clicking on logout...refresh the page and it will login again).....where should I declare such issues ?

**Pull request merged**
